#!/usr/bin/env node
global.chai = require('chai')
global.chai.use(require('sinon-chai'))
global.chai.use(require('chai-uuid'))

const { stub } = require('sinon')
const override = require('override-require')

function validOverrides (request) {
  return ['elasticsearch', 'graphql-request', 'simple-pg'].includes(request)
}

override(validOverrides, request => {
  switch (request.toLowerCase()) {
    case 'elasticsearch':
      return {
        Client: stub()
      }
    case 'graphql-request':
      return {
        GraphQLClient: stub().resolves({})
      }
    case 'simple-pg':
      return stub().returns(stub())
    default:
      return stub()
  }
})
